# Generated by Django 4.0.5 on 2022-06-24 10:49

from django.db import migrations, models
import django.db.models.deletion
import drf_extended.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyParentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('description', models.TextField()),
            ],
            bases=(drf_extended.models.APIMixin, models.Model),
        ),
        migrations.CreateModel(
            name='MyModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=40)),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.myparentmodel')),
            ],
            options={
                'abstract': False,
            },
            bases=(drf_extended.models.APIMixin, models.Model),
        ),
    ]
