name: Lint package

on:
  pull_request:
    branches:
      - main
  release:
    types: [published]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8
      - name: Run flake8
        uses: suo/flake8-github-action@releases/v1
        with:
          checkName: 'lint'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  test:
    runs-on: ubuntu-latest
    needs: [lint]
    strategy:
      matrix:
        python-version: [ "3.7", "3.8", "3.9", "3.10" ]
        django-version: [ ">=3,<3.1", ">=3.1,<3.2", ">=3.2,<4", ">=4,<4.1" ]
        drf-version: [ ">=3.11,<3.12", ">=3.12,<3.13", ">=3.13,<3.14" ]
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install Django${{ matrix.django-version }}
          pip install djangorestframework${{ matrix.drf-version }}
          pip install pytest pytest-cov pytest-djangoapp
      - name: Run pytest
        working-directory: .
        run: pytest
